### ISSUE TITLE
Clear way to Yeller.report() errors from window.onerror?

### ISSUE THREAD

**Issue by tonsky** [yeller/yeller.js#3]
Right now you either setup global error handler via `Yeller.configure()` or report errors from catch block using `Yeller.report()`. What if I want catch-all handler, but I want to specify my on custom data at the moment exception occur.

Case: I have single-page app, and state can change during lifetime of the page. E.g. I can change user, navigate between pages, etc. — without reloading the page. Now I want catch-all error handler to report current user name. I want to specify user name _at the moment exception occurs_, not on the page load. Simply because it’s dynamic and can change.

Do you think it’s possible to have a specialized API call for that?

E.g. `Yeller.configure()` can accept additional `custom_data_callback` parameter that will be called just before sending a report, and this callback should return JS object with custom data one want to add to report.

**Comment by tom-pang** [comment]
@tonsky that seems totally possible for me. I think likely the best mechanism would be having a parameter called `transform`, which is a callback that accepts a formatted error, and returns another one (a formatted error is the js object yeller.js turns into JSON to send to the API). I'll give it a go tomorrow.

**Comment by tom-pang** [comment]
@tonsky see #4. Let me know if that works for you.
